##
## EPITECH PROJECT, 2018
## PROJECT
## File description:
## A simple Makefile to compile functionnal tests
##

CC	=	gcc

compile_src:
	echo "No source to compile\n"

run_test:
	echo "No test\n"

clean:
	$(RM) *.o

fclean:	clean

re:	fclean all

.PHONY: all clean fclean run_test re
