##
## EPITECH PROJECT, 2018
## Makefile
## File description:
## A simple Makefile
##

tests_run:
	$(MAKE) -C ./tests

clean:
	$(MAKE) -C ./tests/ clean

fclean:	clean
	$(MAKE) -C ./tests/ fclean

.PHONY: clean fclean re tests_run
